debug: false
developer_mode: false

primary_asn: "65000"
org_name: Beloved Hyperglass User
site_title: hyperglass
site_description: "{org_name} Network Looking Glass"
site_keywords: [hyperglass, looking glass, routing, bgp]
request_timeout: 30
listen_address: 0.0.0.0
listen_port: 80
cors_origins: []

logging:
  directory: /var/log
  format: json
  max_size: 100 MB

cache:
  host: redis
  port: 6379
  show_text: true
  timeout: 120

web:
  credit:
    enable: true
  dns_provider:
    name: cloudflare
    url: https://cloudflare-dns.com/dns-query
  greeting:
    button: Continue
    enable: true
    file: /etc/hyperglass/greeting.md
    required: true
    title: Welcome
  links:
    - order: 0
      show_icon: true
      side: left
      title: PeeringDB
      url: https://www.peeringdb.com/asn/{primary_asn}
  menus:
    - content: /etc/hyperglass/terms.md
      order: 0
      side: left
      title: Terms
    - content: /etc/hyperglass/help.md
      order: 0
      side: left
      title: Help
  text:
    cache_icon: Cached from {time} UTC
    cache_prefix: "Results cached for "
    complete_time: Completed in {seconds}
    fqdn_error: Unable to resolve {fqdn}
    fqdn_error_button: Try Again
    fqdn_message: Your browser has resolved {fqdn} to
    fqdn_tooltip: Use {protocol}
    no_communities: No Communities
    query_location: Location
    query_target: Target
    query_type: Query Type
    query_vrf: Routing Table
    rpki_invalid: Invalid
    rpki_unknown: No ROAs Exist
    rpki_unverified: Not Verified
    rpki_valid: Valid
    subtitle: Network Looking Glass
    title: hyperglass
    title_mode: logo_subtitle
  theme:
    colors:
      black: "#000"
      blue: "#314cb6"
      cyan: "#118ab2"
      danger: "#d84b4b"
      dark: "#010101"
      error: "#ff6b35"
      gray: "#c1c7cc"
      green: "#35b246"
      light: "#f5f6f7"
      orange: "#ff6b35"
      pink: "#f2607d"
      primary: "#118ab2"
      purple: "#8d30b5"
      red: "#d84b4b"
      secondary: "#314cb6"
      success: "#35b246"
      teal: "#35b299"
      warning: "#edae49"
      white: "#fff"
      yellow: "#edae49"
    default_color_mode: null
    fonts:
      body: Nunito
      mono: Fira Code
